plugins:
  breakpoint:
    executor: central_deployment_agent
    package_name: cloudify-breakpoint-plugin
    package_version: '1.0.0'

dsl_definitions:
  authorization: &authorization
    authorization:
      type: cloudify.types.breakpoint.Authorization
      description: Authorization configurationto control the breakpoint.
      required: true

data_types:

  cloudify.types.breakpoint.Authorization:
    properties:
      users:
        type: list

  cloudify.types.breakpoint.resourceconfig.Breakpoint:
    properties:
      default_break_on_install:
        type: boolean
        default: true
      default_break_on_uninstall:
        type: boolean
        default: true

node_types:

  cloudify.nodes.breakpoint.Breakpoint:
    derived_from: cloudify.nodes.Root
    properties:
      <<: *authorization
      resource_config:
        type: cloudify.types.breakpoint.resourceconfig.Breakpoint
        required: true
    interfaces:
      cloudify.interfaces.lifecycle:
        start: breakpoint.breakpoint_plugin.resources.breakpoint.start
        stop: breakpoint.breakpoint_plugin.resources.breakpoint.stop
      cloudify.interfaces.breakpoint:
        check: breakpoint.breakpoint_plugin.resources.breakpoint.check

workflows:

  set_breakpoint_state:
    mapping: breakpoint.breakpoint_plugin.workflows.state.set_breakpoint_state
    parameters:
      node_ids:
        description: The list of node IDs to open breakpoint for.
        type: list
      node_instance_ids:
        description: The list of node instance IDs to open breakpoint for.
        type: list
      break_on_install:
        description: Specifies if the breakpoint should stop on start lifecycle operation.
        type: boolean
        default: true
      break_on_uninstall:
        description: Specifies if the breakpoint should stop on stop lifecycle operation.
        type: boolean
        default: true
      permanent:
        description: Specifies that this setting of the breakpoints is permanent. If false if will apply only to the next execution.
        type: boolean
        default: false
