plugins:
  breakpoint:
    executor: central_deployment_agent
    package_name: cloudify-breakpoint-plugin
    package_version: '1.0.0'

dsl_definitions:
  authorization: &authorization
    client_config:
      type: cloudify.datatypes.breakpoint.Authorization
      description: Authorization configurationto control the breakpoint.
      required: true

data_types:

  cloudify.types.breakpoint.Authorization:
    properties:
      users:
        type: list

  cloudify.types.breakpoint.resourceconfig.Breakpoint:
    properties:
      default_break_on_start:
        type: boolean
        default: true
      default_break_on_stop:
        type: boolean
        default: true

node_types:

  cloudify.nodes.breakpoint.Breakpoint:
    derived_from: cloudify.nodes.etcd.Base
    properties:
      <<: *authorization
      resource_config:
        type: cloudify.datatypes.breakpoint.resourceconfig.Breakpoint
        required: true
# TODO (marrowne) mapping
#    interfaces:
#      cloudify.interfaces:
#        lifecycle:
#          start:
#          stop:
#        breakpoint:
#          check:

workflows:

  set_breakpoint_state:
# TODO (marrowne) mapping
#    mapping:
    parameters:
      node_id:
        description: The list of node IDs to open breakpoint for.
        type: list
      node_instance_id:
        description: The list of node instance IDs to open breakpoint for.
        type: list
      all_breakpoints:
        description: Override the node (instance) id lists and open all breakpoints.
        type: boolean
        default: false
      break_on_start:
        description: Specifies if the breakpoint should stop on start lifecycle operation.
        type: boolean
        default: true
      break_on_stop:
        description: Specifies if the breakpoint should stop on stop lifecycle operation.
        type: boolean
        default: true
      permanent:
        description: Specifies that this setting of the breakpoints is permanent. If false if will apply only to the next execution.
        type: boolean
        default: false
